#include "PupalupApp.h"
#include "Moose.h"
#include "AppFactory.h"

template<>
InputParameters validParams<PupalupApp>()
{
  InputParameters params = validParams<MooseApp>();
  return params;
}

PupalupApp::PupalupApp(const std::string & name, InputParameters parameters) :
    MooseApp(name, parameters)
{
  srand(processor_id());

  Moose::registerObjects(_factory);
  PupalupApp::registerObjects(_factory);

  Moose::associateSyntax(_syntax, _action_factory);
  PupalupApp::associateSyntax(_syntax, _action_factory);
}

PupalupApp::~PupalupApp()
{
}

void
PupalupApp::registerApps()
{
  registerApp(PupalupApp);
}

void
PupalupApp::registerObjects(Factory & factory)
{
}

void
PupalupApp::associateSyntax(Syntax & syntax, ActionFactory & action_factory)
{
}
